
package smart.home.security.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import smart.home.security.model.Device;
import smart.home.security.model.Devices;
import smart.home.security.utilities.DeviceTableModel;

public class RemoveDevicePanel extends javax.swing.JPanel {

    public RemoveDevicePanel()
    {
        initComponents();

        List<Device> devices = Devices.getInstance().getDevices();
        DefaultTableModel model = DeviceTableModel.defaultTableModel(devices);
        removeDeviceTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        removeButton = new javax.swing.JButton();
        cancelRemoveButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        removeDeviceTable = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remove Device", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(408, 309));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        removeButton.setText("Remove");
        removeButton.setToolTipText("Are you sure");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, -1));

        cancelRemoveButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        cancelRemoveButton.setText("Cancel");
        cancelRemoveButton.setToolTipText("");
        cancelRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRemoveButtonActionPerformed(evt);
            }
        });
        add(cancelRemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, -1));

        removeDeviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                                               Device Name"
            }
        ));
        jScrollPane3.setViewportView(removeDeviceTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 230));
    }// </editor-fold>//GEN-END:initComponents
    private SmartHomeSecurityFrame getSmartHomeSecurityFrame() {
        return (SmartHomeSecurityFrame) SwingUtilities.getWindowAncestor(this);
    }
    private void cancelRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRemoveButtonActionPerformed
        // TODO add your handling code here:
        getSmartHomeSecurityFrame().replaceFramePanel(new MainPanel());
    }//GEN-LAST:event_cancelRemoveButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

        int selectedIndex = removeDeviceTable.getSelectedRow();
        if (selectedIndex >= 0) 
        {
            Device device = Devices.getInstance().getDevices().get(selectedIndex);
            Devices.getInstance().removeDevice(device);
            
            String str = evt.getActionCommand();
            if (str.equals("Remove")) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure you want to remove this device", "Roseindia.net", JOptionPane.YES_NO_OPTION) == 0) {
                    JOptionPane.showMessageDialog(this, "The Device Has Been Sucessfully Removed");
//                    JOptionPane.showMessageDialog(null, "You clicked on \"Ok\" button", "Roseindia.net", 1);
                    getSmartHomeSecurityFrame().replaceFramePanel(new MainPanel());
                } else {
                    getSmartHomeSecurityFrame().replaceFramePanel(new MainPanel());
//                    JOptionPane.showMessageDialog(null, "You clicked on \"Cancel\" button", "Roseindia.net", 1);
                }
            } else if (str.equals("Show \"Yes/No/Cancel\" dialog box")) {
                JOptionPane.showConfirmDialog(null, "This is the \"Yes/No/Cancel\" message dialog box.");
            }
            
            
            
            
            
//            JOptionPane.showMessageDialog(this, "Device removed");
//            getSmartHomeSecurityFrame().replaceFramePanel(new MainPanel());
        }
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelRemoveButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton removeButton;
    private javax.swing.JTable removeDeviceTable;
    // End of variables declaration//GEN-END:variables
}
