/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.home.security.view;

import java.awt.Component;
import java.awt.GridLayout;
import smart.home.security.model.Device;
import smart.home.security.model.Devices;
import smart.home.security.utilities.DeviceManager;
import smart.home.security.utilities.DeviceSocketManager;

/**
 *
 * @author chana
 */
public class SmartHomeSecurityFrame extends javax.swing.JFrame {

    /**
     * Creates new form SmartHomeSecurityFrame
     */
    public SmartHomeSecurityFrame() {
        initComponents();
        pack();
        showMainPanel();
        setResizable(false);        
    }

    /**
     * Replaces the JFrame with JPanel
     *
     * @param component
     */
    public void replaceFramePanel(Component component) {
        getContentPane().removeAll();
        setLayout(new GridLayout(1, 1));
        add(component);
        getContentPane().repaint();
        pack();
    }

    /**
     * Display the main panel on the frame.
     */
    private void showMainPanel() {
        replaceFramePanel(new MainPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Load the devices from file.
        DeviceManager.loadDevices();                
        
        // Save the devices when the JVM shuts down.
        Runtime.getRuntime().addShutdownHook(new DeviceManager());
        
        // Establish connection to all devices.               
        DeviceSocketManager.getInstance().connectDevices();
        Runtime.getRuntime().addShutdownHook(DeviceSocketManager.getInstance());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SmartHomeSecurityFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
